### ISSUE TITLE
libnss3 missing

### ISSUE THREAD

**Issue by GreenLord** [greenbananaCH/threema-desktop-app#1]
Tryed it on Lubuntu 20.x and Kubuntu 20.x. The file "libnss3.so" is missing. Trying to installing it, but it already installed (2:3.49.1-1ubuntu1.5).

**Comment by GreenLord** [comment]
OK, looks like, the program is looking for a 32bit version of that missing lib. Since my Ubuntu is a 64bit OS, this won't work. Maybe a final compiled version for 64bit, will solve this (the easiest way, i guess).

**Comment by langhard** [comment]
Let's try this. I have just built an x64 version of the app. Give me some feedback if this solves your problems. Greetings Jürg

Build-Status: https://drone.greenbanana.ch/greenbananaCH/threema-desktop-app/11

**Comment by GreenLord** [comment]
Ok, dieser Build funktioniert hier (aktuelles Kubuntu und Lubuntu, 20.xx.x). Aber ich muss gestehen, ich habe einen Standaloneclient erwartet, der in Richtung OpenMittsu ( https://github.com/blizzard4591/openMittsu ) geht und nicht einen Client, der weiterhin das Handy benötigt ;-).

So oder so, dein Client funktioniert und ich konnte schon zwei andere dafür begeistern und beide freuen sich wie Bolle :-P. Aber leider, für mich nicht das, was ich suche.

**Comment by langhard** [comment]
The desktop client I provide is analogous to the WhatsApp client. The official progressive web app from Threema, provided as an installable version, packaged with Elektron.

More info (in German): https://langhard.ch/download-threema-desktop-client-app/
